# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded gdal 1.0 [list load [file join $dir gdal.so]]
package ifneeded gdalconst 1.0 [list load [file join $dir gdalconst.so]]
package ifneeded ogr 1.0 [list load [file join $dir ogr.so]]
package ifneeded osr 1.0 [list load [file join $dir osr.so]]
